import { StyleSheet } from "react-native";
import { colors } from "../../../theme/colors";
import { spacing } from "../../../theme/spacing";
import { typography } from "../../../theme/typography";

export const athleteEvaluationScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: { padding: spacing.xs },
  headerTitle: {
    ...typography.h3,
    color: colors.foreground,
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: { width: 40 },
  athleteInfo: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.md,
  },
  athleteAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.primary[100],
    alignItems: "center",
    justifyContent: "center",
  },
  athleteName: { ...typography.h4, color: colors.foreground },
  athleteOrg: { ...typography.small, color: colors.muted.foreground },
  tabs: {
    flexDirection: "row",
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tab: {
    flex: 1,
    paddingVertical: spacing.md,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: { borderBottomColor: colors.primary.DEFAULT },
  tabText: {
    ...typography.body,
    color: colors.muted.foreground,
    fontWeight: "600",
  },
  tabTextActive: { color: colors.primary.DEFAULT },
  content: { flex: 1, paddingHorizontal: spacing.lg },
  overallCard: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  overallLabel: {
    ...typography.body,
    color: colors.muted.foreground,
    marginBottom: spacing.sm,
  },
  overallRating: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  overallValue: {
    ...typography.h1,
    color: colors.foreground,
    fontWeight: "700",
  },
  categorySection: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  categoryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  categoryTitle: { ...typography.h4, color: colors.foreground },
  categoryAverage: {
    ...typography.h4,
    color: colors.primary.DEFAULT,
    fontWeight: "700",
  },
  ratingItem: { marginBottom: spacing.md },
  ratingLabel: {
    ...typography.small,
    color: colors.foreground,
    marginBottom: spacing.xs,
    fontWeight: "600",
  },
  ratingSlider: { flexDirection: "row", gap: 4, marginBottom: spacing.xs },
  ratingDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.muted.DEFAULT,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ratingDotActive: {
    backgroundColor: colors.primary.DEFAULT,
    borderColor: colors.primary.DEFAULT,
  },
  ratingValue: {
    ...typography.small,
    color: colors.muted.foreground,
    textAlign: "right",
  },
  textSection: { marginTop: spacing.lg },
  textLabel: {
    ...typography.body,
    color: colors.foreground,
    marginBottom: spacing.sm,
    fontWeight: "600",
  },
  textInput: {
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: spacing.md,
    ...typography.body,
    color: colors.foreground,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 80,
    textAlignVertical: "top",
  },
  submitButton: { marginTop: spacing.xl, marginBottom: spacing.lg },
  historyCard: {
    marginTop: spacing.md,
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  historyDate: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: "600",
  },
  historyCoach: {
    ...typography.small,
    color: colors.muted.foreground,
    marginTop: spacing.xs,
  },
  historyRating: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: colors.status.warning + "20",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 12,
  },
  historyRatingText: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: "700",
  },
  historyRatings: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  historyRatingItem: { alignItems: "center" },
  historyRatingLabel: {
    ...typography.tiny,
    color: colors.muted.foreground,
    marginBottom: spacing.xs,
  },
  historyRatingValue: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: "600",
  },
  historyNotes: {
    ...typography.body,
    color: colors.foreground,
    marginTop: spacing.md,
    lineHeight: 20,
  },
  emptyState: { padding: spacing.xl, alignItems: "center" },
  emptyText: { ...typography.body, color: colors.muted.foreground },
  bottomSpacer: { height: spacing.xl },
});
