import { StyleSheet } from "react-native";
import {
  colors,
  spacing,
  borderRadius,
  fontSize,
  shadows,
} from "../../../constants/design-tokens";
import { globalStyles } from "../../../styles/global.styles";

export const homeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray[50],
  },
  header: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xl,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "nowrap",
  },
  headerLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginRight: spacing.md,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: spacing.md,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
  },
  textContainer: {
    flex: 1,
  },
  welcomeText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.9)",
  },
  userName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ffffff",
  },
  notificationButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  notificationBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#ffffff",
  },
  quickActionsContainer: {
    paddingHorizontal: spacing.lg,
    marginTop: 20,
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -spacing.xs,
    marginBottom: spacing.md,
  },
  quickActionItem: {
    width: "25%",
    alignItems: "center",
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.md,
  },
  quickActionIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xs,
    ...shadows.sm,
  },
  quickActionLabel: {
    fontSize: 12,
    color: colors.gray[700],
    textAlign: "center",
  },
  section: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.foreground,
    marginBottom: spacing.md,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  seeAllText: {
    fontSize: 14,
    color: colors.primary.DEFAULT,
    fontWeight: "600",
  },
  featuredCard: {
    borderRadius: borderRadius["2xl"],
    padding: spacing.xl,
    ...shadows.xl,
  },
  featuredBadge: {
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    alignSelf: "flex-start",
    marginBottom: spacing.md,
  },
  featuredBadgeText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#ffffff",
  },
  featuredTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: spacing.md,
  },
  featuredInfo: {
    gap: spacing.sm,
  },
  featuredInfoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  featuredInfoText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.9)",
  },
  matchCard: {
    backgroundColor: "#ffffff",
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  matchTime: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  matchTimeText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primary.DEFAULT,
  },
  matchPlayers: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.sm,
  },
  playerName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.foreground,
    flex: 1,
  },
  vsText: {
    fontSize: 14,
    fontWeight: "bold",
    color: colors.gray[400],
    marginHorizontal: spacing.sm,
  },
  matchInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  matchInfoText: {
    fontSize: 13,
    color: colors.gray[600],
  },
  statsRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    alignItems: "center",
    ...shadows.md,
  },
  statValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: colors.foreground,
    marginTop: spacing.sm,
  },
  statLabel: {
    fontSize: 14,
    color: colors.gray[600],
    marginTop: spacing.xs,
  },
});
