import { StyleSheet } from "react-native";
import { colors } from "../../../theme/colors";
import { spacing } from "../../../theme/spacing";
import { typography } from "../../../theme/typography";

export const performanceAnalyticsScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  headerTitle: {
    ...typography.h1,
    color: "#ffffff",
    marginBottom: spacing.xs,
  },
  headerSubtitle: { ...typography.body, color: "#ffffff", opacity: 0.9 },
  athleteList: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexGrow: 0,
  },
  athleteCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: 12,
    padding: spacing.sm,
    marginRight: spacing.sm,
    minWidth: 140,
    maxWidth: 180,
    borderWidth: 1,
    borderColor: colors.border,
  },
  athleteCardSelected: {
    borderColor: colors.primary.DEFAULT,
    borderWidth: 2,
    backgroundColor: colors.primary[50],
  },
  athleteAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary[100],
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.xs,
  },
  athleteAvatarText: {
    ...typography.body,
    color: colors.primary.DEFAULT,
    fontWeight: "700",
  },
  athleteCardInfo: { flex: 1 },
  athleteCardName: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: "600",
    marginBottom: spacing.xs,
  },
  athleteCardStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  athleteCardStat: { ...typography.small, color: colors.muted.foreground },
  athleteCardTrend: { marginLeft: -4 },
  content: { flex: 1, paddingHorizontal: spacing.lg },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: spacing.lg,
  },
  metricCard: {
    flex: 1,
    minWidth: 150,
    maxWidth: "48%",
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  metricIcon: { marginBottom: spacing.sm },
  metricValue: {
    ...typography.h2,
    color: colors.foreground,
    fontWeight: "700",
    marginBottom: spacing.xs,
  },
  metricLabel: {
    ...typography.small,
    color: colors.muted.foreground,
    textAlign: "center",
  },
  metricTrend: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    borderRadius: 8,
  },
  metricTrendUp: { backgroundColor: colors.status.success + "20" },
  metricTrendDown: { backgroundColor: colors.status.error + "20" },
  metricTrendText: { ...typography.tiny, fontWeight: "600" },
  metricTrendTextUp: { color: colors.status.success },
  metricTrendTextDown: { color: colors.status.error },
  sectionTitle: {
    ...typography.h3,
    color: colors.foreground,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
  },
  trendSection: { marginTop: spacing.md },
  trendChart: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    height: 200,
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  trendBar: { flex: 1, alignItems: "center" },
  trendBarContainer: { flex: 1, width: "80%", justifyContent: "flex-end" },
  trendBarFill: {
    width: "100%",
    backgroundColor: colors.primary.DEFAULT,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    minHeight: 20,
  },
  trendLabel: {
    ...typography.tiny,
    color: colors.muted.foreground,
    marginTop: spacing.xs,
  },
  trendLegend: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: spacing.md,
    gap: spacing.lg,
  },
  trendLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  trendLegendDot: { width: 8, height: 8, borderRadius: 4 },
  trendLegendText: { ...typography.small, color: colors.muted.foreground },
  matchesSection: { marginTop: spacing.md },
  matchCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  matchHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.xs,
  },
  matchDate: { ...typography.small, color: colors.muted.foreground },
  matchResult: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: 8,
  },
  matchResultWin: { backgroundColor: colors.status.success + "20" },
  matchResultLoss: { backgroundColor: colors.status.error + "20" },
  matchResultText: { ...typography.tiny, fontWeight: "700" },
  matchResultTextWin: { color: colors.status.success },
  matchResultTextLoss: { color: colors.status.error },
  matchOpponent: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: "600",
    marginBottom: spacing.xs,
  },
  matchFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  matchScore: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: "700",
  },
  matchTournament: { ...typography.small, color: colors.muted.foreground },
  evaluationSection: { marginTop: spacing.md },
  evaluationCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  evaluationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.xs,
  },
  evaluationDate: { ...typography.small, color: colors.muted.foreground },
  evaluationRating: {
    backgroundColor: colors.primary[50],
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: 8,
  },
  evaluationRatingText: {
    ...typography.body,
    color: colors.primary.DEFAULT,
    fontWeight: "700",
  },
  evaluationNotes: {
    ...typography.body,
    color: colors.foreground,
    lineHeight: 20,
  },
  noData: {
    ...typography.body,
    color: colors.muted.foreground,
    textAlign: "center",
    paddingVertical: spacing.lg,
  },
  bottomSpacer: { height: spacing.xl },
});
