import { StyleSheet } from "react-native";
import { colors } from "../../../theme/colors";
import { spacing } from "../../../theme/spacing";
import { typography } from "../../../theme/typography";

export const createTrainingPlanScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: { padding: spacing.xs },
  headerTitle: {
    ...typography.h3,
    color: colors.foreground,
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: { width: 40 },
  stepsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    padding: spacing.md,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  stepItem: { alignItems: "center", flex: 1 },
  stepCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.muted.DEFAULT,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xs,
  },
  stepCircleActive: { backgroundColor: colors.primary.DEFAULT },
  stepCircleCompleted: { backgroundColor: colors.status.success },
  stepLabel: {
    ...typography.tiny,
    color: colors.muted.foreground,
    textAlign: "center",
  },
  stepLabelActive: { color: colors.primary.DEFAULT, fontWeight: "600" },
  stepLabelCompleted: { color: colors.status.success },
  content: { flex: 1, paddingHorizontal: spacing.lg },
  stepContent: { paddingVertical: spacing.lg },
  sectionTitle: {
    ...typography.h3,
    color: colors.foreground,
    marginBottom: spacing.lg,
  },
  formGroup: { marginBottom: spacing.lg },
  label: {
    ...typography.body,
    color: colors.foreground,
    marginBottom: spacing.sm,
    fontWeight: "600",
  },
  input: {
    backgroundColor: colors.input,
    borderRadius: 8,
    padding: spacing.md,
    ...typography.body,
    color: colors.foreground,
    borderWidth: 1,
    borderColor: colors.border,
  },
  textArea: { height: 100, textAlignVertical: "top" },
  athleteItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.md,
    backgroundColor: colors.card,
    borderRadius: 12,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  athleteItemSelected: {
    borderColor: colors.primary.DEFAULT,
    borderWidth: 2,
    backgroundColor: `${colors.primary[50]}`,
  },
  athleteInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    flex: 1,
  },
  athleteAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary[100],
    alignItems: "center",
    justifyContent: "center",
  },
  athleteAvatarText: {
    ...typography.body,
    color: colors.primary.DEFAULT,
    fontWeight: "700",
  },
  athleteName: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: "600",
  },
  athleteOrg: { ...typography.small, color: colors.muted.foreground },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
  },
  radioCircleSelected: {
    borderColor: colors.primary.DEFAULT,
    backgroundColor: colors.primary.DEFAULT,
  },
  addContainer: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  addButton: {
    backgroundColor: colors.primary.DEFAULT,
    paddingHorizontal: spacing.lg,
    borderRadius: 8,
    justifyContent: "center",
  },
  addButtonText: {
    ...typography.body,
    color: colors.primary.foreground,
    fontWeight: "600",
  },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.md,
    backgroundColor: colors.card,
    borderRadius: 8,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  listItemText: { ...typography.body, color: colors.foreground, flex: 1 },
  removeButton: {
    ...typography.small,
    color: colors.status.error,
    fontWeight: "600",
  },
  reviewSection: {
    marginBottom: spacing.lg,
    padding: spacing.md,
    backgroundColor: colors.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reviewLabel: {
    ...typography.small,
    color: colors.muted.foreground,
    marginBottom: spacing.xs,
    fontWeight: "600",
  },
  reviewValue: { ...typography.body, color: colors.foreground },
  reviewListItem: {
    ...typography.body,
    color: colors.foreground,
    marginTop: spacing.xs,
  },
  footer: {
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  nextButton: { width: "100%" },
});
